### PR TITLE
feat(search): clear search text when localSearchBox exit

### PR DESCRIPTION
**Pull request by zonemeen**
It looks weird if the search text is not cleared when localSearchBox exits.

### CODE REVIEW

**Comment by brc-dd** [comment]
Hey, this was intentional, so you can sort of resume search. Also when the box is reopened, that text is already selected so if you start typing it gets replaced. It will be better to disable this only behind some flag like `disableQueryPersistence` (defaults false).

**Comment by zonemeen** [comment]
Thanks for your reply. So how should I configure to disable this?

**Comment by brc-dd** [comment]
You can add an option similar to this:

https://github.com/vuejs/vitepress/blob/1769d329cc1f517136d9a543385edce335e5dd24/types/default-theme.d.ts#L299

Then before close is emitted just set `filterText` to `''`.

**Comment by zonemeen** [comment]
OK, I understand. Can I submit this new feature?

**Comment by brc-dd** [comment]
Yeah sure.

**Comment by zonemeen** [comment]
Ok, I will resubmit the code on this branch when I have time later. Thanks for your patience and guidance.😄

**Pull request closed without merging**
