### PR TITLE
Preloading critical style-sheets for improved performance 🚤  

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
This is inspired from `Next.js`.
[Preload critical stylesheets to improve loading speed](https://web.dev/preload-critical-assets/).

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Comment by userquin** [comment]
@brc-dd I use this, LGTM: for example, I also apply some non blocking trick to css resources: https://github.com/vitest-dev/vitest/blob/main/docs/.vitepress/scripts/assets.ts#L40

@sanjaiyan-dev I use this with Link header (server side) to allow the browser to load some resources fast (before browser starts parsing the html)

**Comment by sanjaiyan-dev** [comment]
> @brc-dd I use this, LGTM: for example, I also apply some non blocking trick to css resources: https://github.com/vitest-dev/vitest/blob/main/docs/.vitepress/scripts/assets.ts#L40
> 
> @sanjaiyan-dev I use this with Link header (server side) to allow the browser to load some resources fast (before browser starts parsing the html)

Hi,

So it is already implemented in vitepress ?

**Comment by userquin** [comment]
> So it is already implemented in vitepress ?

I think no, I should check the code...

**Comment by sanjaiyan-dev** [comment]
> @brc-dd I use this, LGTM: for example, I also apply some non blocking trick to css resources: https://github.com/vitest-dev/vitest/blob/main/docs/.vitepress/scripts/assets.ts#L40
> 
> @sanjaiyan-dev I use this with Link header (server side) to allow the browser to load some resources fast (before browser starts parsing the html)

Sorry if I am wrong, in SSG generation I thought better to add `link` tag that adding header :)

**Comment by sanjaiyan-dev** [comment]
> @brc-dd I use this, LGTM: for example, I also apply some non blocking trick to css resources: https://github.com/vitest-dev/vitest/blob/main/docs/.vitepress/scripts/assets.ts#L40
> 
> @sanjaiyan-dev I use this with Link header (server side) to allow the browser to load some resources fast (before browser starts parsing the html)

Sorry if I am wrong, in SSG generation I thought better to add `link` tag that adding header :)

**Pull request merged**
