### PR TITLE
feat: import code snippet with region (#237)

### LINKED ISSUE #237: Import code snippet with region
**Is your feature request related to a problem? Please describe.**
Require functionality to import code snippet with region as in [VuePress feature](https://vuepress.vuejs.org/guide/markdown.html#import-code-snippets).

**Describe the solution you'd like**
Adapt the same solution as in VuePress feature here.

### PR DESCRIPTION
**Pull request by mysticmind**
- Add functionality for import code snippet with region
- Add docs for import code snippet

Both the above are adapted from the VuePress functionality and docs.

Closes #237

### CODE REVIEW

**Comment by mysticmind** [comment]
@yyx990803 @kiaking I attempted to add docs for the "import code snippet" as a follow on commit to my original PR but the CI builds are failing due to the location of the files i.e. I tried placing it under `docs\snippets\snippet.js` and then in markdown, I added <<< ./docs/snippets/snippet.js `, it had failed.  Also attempted to move it under `__tests__/node/markdown/fragments/snippet.js`  with the line in markdown as `<<< ./../__tests__/node/markdown/fragments/snippet.js{2}`, still it is failing.

Any thoughts on how to fix this?

**Comment by mysticmind** [comment]
Quick note, this PR is ready for review and next steps.

**Comment by mysticmind** [comment]
Any idea when this PR would be reviewed for next steps?

**Review by kiaking — APPROVED** [review]
Looking good! Thanks for the awesome PR 🙌

**Pull request merged**
