### PR TITLE
feat: add code-group title

### PR DESCRIPTION
**Pull request by lavecoral**
Add same custom title as custom container to code group

### CODE REVIEW

**Comment by MarkusKeck** [comment]
Isn't this the same as #1834 

It got added in the latest version 1.0.0-alpha.47 (2023-02-20)
https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md

**Comment by brc-dd** [comment]
@MarkusKeck No, this one adds something like a caption to a code-block:

image

I am still not sure if we'll be adding this though. For images this might make sense, but for code groups/blocks I don't think this has any use case.

**Comment by MarkusKeck** [comment]
@brc-dd Thanks for clarification, I also dont really see a usecase, if you want the whole filename you can just add it to the title.

**Comment by MarkusKeck** [comment]
@lavecoral Some of the tests have failed. You can check this manually before pushing:

`pnpm check`

If something is not formatted correctly run: `prettier --check .`
After that `prettier --write <filename>`

**Comment by lavecoral** [comment]
@brc-dd link that: https://docs.spring.io/spring-security/reference/migration/servlet/session-management.html

**Pull request closed without merging**
