### PR TITLE
feat: add print style

### LINKED ISSUE #593: export to pdf
### Is your feature request related to a problem? Please describe.

not really

### Describe the solution you'd like

a plugin or built-in feature of vitepress that I can export the document to PDF, to annotate offline

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kecrily**
close #593 #612

### CODE REVIEW

**Comment by kiaking** [comment]
@kecrily Thanks a lot! Do you know why it doesn't show code block background color? I get this PDF wen printed.

[Markdown Extensions _ VitePress.pdf](https://github.com/vuejs/vitepress/files/8898091/Markdown.Extensions._.VitePress.pdf)

If this is somekind of printing limitation for saving inks I'm fine but wanted to check in.

**Comment by kecrily** [comment]
It did not meet expectations and I didn't make changes to this. Is it working properly in print preview? What browser are you using again?

I use Chrome, and this is the pdf I get.

[Markdown.pdf](https://github.com/vuejs/vitepress/files/8898247/Markdown.pdf)


---

Also in this file I found some components whose styles I did not take into account, such as the collapsed box and the code block that overflows the page. I need to tweak them a bit and check that the background color of this code block is not showing.

**Comment by kiaking** [comment]
I'm using Chrome too. Strange 🤔 Well it's still readable so not a big deal though.

> Also in this file I found some components whose styles I did not take into account, such as the collapsed box and the code block that overflows the page. I need to tweak them a bit and check that the background color of this code block is not showing.

OK gotcha. I'll check once again once this changes arive 👍

**Comment by brc-dd** [comment]
>  Do you know why it doesn't show code block background color?

You probably have "background graphics" disabled in print settings:

image

**Pull request closed without merging**
