### PR TITLE
fix(theme): don't show footer without sidebar on doc layout

### PR DESCRIPTION
**Pull request by FuZhouJohn**
When I don't use sidebar, the doc layout will show footer.

### CODE REVIEW

**Comment by kiaking** [comment]
I like how it look with footer for example in this page.
https://main.vitejs.dev/plugins/

So, I like to keep footer in sidebarless doc page 🤔 

I haven't check but is this misunderstanding comes from some where in the docs?

**Comment by FuZhouJohn** [comment]
> 

https://vitepress.vuejs.org/guide/theme-footer.html
> Note that footer will not be displayed when the page layout is set to doc.

**Comment by FuZhouJohn** [comment]
> 我喜欢它的外观与页脚，例如在这个页面。 https://main.vitejs.dev/plugins/
> 
> 所以，我喜欢在无侧边栏文档页面中保留页脚🤔
> 
> 我没有检查，但这种误解是否来自文档中的某些地方？

@kiaking
 
[https://vitepress.vuejs.org/guide/theme-footer.html](https://vitepress.vuejs.org/guide/theme-footer.html)

> Note that footer will not be displayed when the page layout is set to doc.

**Comment by FuZhouJohn** [comment]
> I like how it look with footer for example in this page. https://main.vitejs.dev/plugins/
> 
> So, I like to keep footer in sidebarless doc page 🤔
> 
> I haven't check but is this misunderstanding comes from some where in the docs?

@kiaking 

[https://vitepress.vuejs.org/guide/theme-footer.html](https://vitepress.vuejs.org/guide/theme-footer.html)

> Note that footer will not be displayed when the page layout is set to doc.

**Comment by kiaking** [comment]
Oh I see, we should change that docs instead saying that it gets hidden when there is sidebar 😅

**Pull request closed without merging**
