### PR TITLE
fix: make MD includes work with rewrites

### PR DESCRIPTION
**Pull request by chgeo**
Fixes https://github.com/vuejs/vitepress/issues/1961

### CODE REVIEW

**Comment by brc-dd** [comment]
Hey can you run `pnpm format` and commit changes?

**Comment by chgeo** [comment]
> Hey can you run `pnpm format` and commit changes?

Done.

**Comment by chgeo** [comment]
@brc-dd Can we merge this?  Anything that is missing?

**Comment by brc-dd** [comment]
> Anything that is missing?

I need to test it. Also, Evan was working on dynamic routes which are sort of linked. So I'm trying to avoid conflicts currently. Let him finish. We can merge this later.

Also, includes work with rewrites. But currently they are being resolved to the final path. Like if you have rewritten `foo/a.md` to `bar/a.md`, and you want to include `b.md`, you need to keep it in `bar/`.

**Comment by chgeo** [comment]
Alright, then I'll be patient :)

**Review by brc-dd — APPROVED** [review]

**Pull request merged**
