### PR TITLE
chore: use pnpx init project

### PR DESCRIPTION
**Pull request by btea**
### Additional Context

---

> [!TIP]
> The author of this PR can publish a _preview release_ by commenting `/publish` below.

### CODE REVIEW

**Comment by brc-dd** [comment]
You need to install vitepress first. Even if you use pnpx, you'll need to manually install vitepress. The init script doesn't add it in deps for you. The prerequisite part tells to install vitepress first.

**Comment by btea** [comment]
According to the documentation, using `pnpx` does not require any dependencies to be installed locally. Am I misunderstanding this description?

image

**Comment by brc-dd** [comment]
vitepress needed you to install vitepress first

**Comment by btea** [comment]
I see, thanks for the quick response.

**Pull request closed without merging**
