### PR TITLE
fix(theme): close menu on route change

### PR DESCRIPTION
**Pull request by zonemeen**
fix https://github.com/vuejs/vitepress/issues/872

### CODE REVIEW

**Comment by zonemeen** [comment]
> The issue is still there. Check the deploy preview.

hi, I have modified the pr

**Comment by brc-dd** [comment]
@zonemeen Still not working:

https://user-images.githubusercontent.com/40380293/176990981-05f8c6ac-b1ef-4f52-9617-2de1d0b747f9.mp4

**Comment by brc-dd** [comment]
Hi! You're changing the functionality of sidebar not the menu.

**Comment by zonemeen** [comment]
> 

I originally thought #872 was describing the problem I'm fixing, I misunderstood 🤣

**Comment by brc-dd** [comment]
Yeah, there are lot of menus. It gets confusing at times! 😅

**Pull request merged**
