### PR TITLE
feat(build): add `useWebFonts` option

### LINKED ISSUE #1523: Use web fonts on web containers
Context: Currently we emit a bunch of font files to dist while building. This causes error in StackBlitz if the user doesn't have subscription.

Solution: Add an option to use Inter from Google Fonts. And enable it by default on webcontainers. Env can be checked [like this](https://github.com/vitest-dev/vitest/pull/763/files#diff-c381e6de43a918512ead544ce9b936666a7066fdfddd83c19221b433a01e4ee4R67).

### PR DESCRIPTION
**Pull request by brc-dd**
fixes #1523

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hi @brc-dd! Just wanted to give you a heads up that the change to `font-synthesis: style` is causing the Italics to be _very_ slanted 🤔 Is this intentional? I can open an Issue if not 🙂 :

CleanShot 2022-11-04 at 13 53 43@2x

**Comment by rijkvanzanten** [comment]
(Example above is in Arc Version 0.74.1 (35450), Chromium Engine Version 107.0.5304.88. I don't have the Inter font installed on my Mac)

**Comment by brc-dd** [comment]
Yeah, I was working on something too yesterday and saw this. IG we can revert that option to default to none and inside the webfont-marker we can set it as style. (Inter on Google Fonts has no italics.)

**Comment by brc-dd** [comment]
Feel free to create a PR, or I will do it tomorrow (it's nearly midnight at my place).

**Comment by rijkvanzanten** [comment]
> Feel free to create a PR, or I will do it tomorrow (it's nearly midnight at my place).

I'm currently moving so I'm not sure if I can get to doing much actual coding either 😁 Whoever gets to it first!

**Comment by rijkvanzanten** [comment]
Also relying on Google Fonts hosted fonts for Inter might have some other nastier downsides, but lets have that discussion on https://github.com/vuejs/vitepress/issues/1523#issuecomment-1303964015 instead 🙂

**Pull request merged**
