### PR TITLE
docs: modify the example usage of postcssIsolateStyles

### PR DESCRIPTION
**Pull request by luohuidong**

### CODE REVIEW

**Comment by brc-dd** [comment]
Can you explain why this is needed? It should working fine for me without spreading.

**Comment by luohuidong** [comment]
If we don't use the spreading, maybe the `plugins` should be an array not a object: 

```js
import { postcssIsolateStyles } from "vitepress";

export default {
  plugins: [
     postcssIsolateStyles()
  ],
};
```

**Comment by luohuidong** [comment]
If the plugins is an object, I think it is a syntax error：

image

**Comment by brc-dd** [comment]
Object syntax won't work. It needs key to be "a Node.js module name, a path to a JavaScript file that is relative to the directory of the PostCSS config file, or an absolute path to a JavaScript file". postcssIsolateStyles is a named export from vitepress. Object format cannot handle that.

**Comment by luohuidong** [comment]
I agree it should be an array instead, so i close this pr.

**Comment by brc-dd** [comment]
I updated that here itself. No need to create separate PR. Thanks

**Pull request merged**
