### PR TITLE
fix: export default theme type

### PR DESCRIPTION
**Pull request by Estelle00**

### CODE REVIEW

**Comment by brc-dd** [comment]
Fixes: https://github.com/vuejs/vitepress/issues/483#issuecomment-1006273672

**Comment by yyx990803** [comment]
I realized this file is no longer necessary - you can just do `import { DefaultTheme } from 'vitepress'`.

**Comment by brc-dd** [comment]
> I realized this file is no longer necessary - you can just do `import { DefaultTheme } from 'vitepress'`.

@yyx990803 That's just the `DefaultTheme` interface, not the actual defaultTheme.

**Comment by yyx990803** [comment]
Thanks, #494 is close but the `Theme` interface is meant as a constraint type instead of the actual type of the default theme. See https://github.com/vuejs/vitepress/commit/eabf6d2aa69d2a5452042bbb59edbbbc95aece87

**Pull request closed without merging**
