### PR TITLE
chore: make scripts consistent across platforms

### PR DESCRIPTION
**Pull request by kecrily**
Contributors using Windows can get a script that behaves the same as other systems without any configuration

ref https://pnpm.io/cli/run#shell-emulator

### CODE REVIEW

**Comment by kiaking** [comment]
@brc-dd Is this good idea? I'm not on Windows so want some insight 😳 If it works for windows user the best way, I don't have reason to not merge it 👍

**Comment by brc-dd** [comment]
Yes, we can merge this. Well, we only have one such script (`dev-node`), all other should work fine on Windows without this setting too.

**Comment by brc-dd** [comment]
Better create this PR against the `next-theme` branch.

**Comment by kecrily** [comment]
OK, but I don't know why I can't change the base branch of the PR. I just sent a ticket to GitHub.

Can you change it? If you can, please help me out. If not, I'll have to create another PR.

**Comment by kiaking** [comment]
I did change it! But, now we have conflicts 👀 Maybe it would be faster to just create a new one?

**Comment by kecrily** [comment]
I was able to change it after you did, but I still can't change a PR that no one has changed. What a strange problem.

**Comment by kecrily** [comment]
Ok, create a new one.

**Pull request closed without merging**
