### PR TITLE
fix(build): don't process md files in public dir

### PR DESCRIPTION
**Pull request by zonemeen**
fix https://github.com/vuejs/vitepress/issues/2629

### CODE REVIEW

**Comment by brc-dd** [comment]
Ah, it will be bit complex 😅 `publicDir` is actually configurable via vite config. Will need to handle that.

**Comment by zonemeen** [comment]
I'll continue to work on it later when I have more time.

**Comment by brc-dd** [comment]
Cool, I don't think it will be exactly possible to support that. Since, vite config can be in a separate file and the way code is laid out resolvePages is called outside plugin contexts too. Using configResolved hook is a no go. What we can probably do is introduce a vitepress level publicDir and discard whatever there is in vite config.

**Comment by zonemeen** [comment]
It is indeed necessary to introduce a vitepress level `publicDir`.🤔Can create a new issue about this new feature.

**Comment by brc-dd** [comment]
I'm reopening #2526. Let's track this there.

**Comment by zonemeen** [comment]
Okay! I'll change the code in this branch when `publicDir` is supported.

**Pull request closed without merging**
