### PR TITLE
fix: simple-git-hooks not working

### PR DESCRIPTION
**Pull request by zonemeen**
It's not clear from which version my local `simple-git-hooks` is not working, I need to update `simple-git-hooks` manually by myself.

So add postinstall script, copied from [vue-core](https://github.com/vuejs/core/blob/d2c3d8b70b2df6e16f053a7ac58e6b04e7b2078f/package.json#LL39C6-L39C17)

### CODE REVIEW

**Comment by brc-dd** [comment]
Don't add that. At vue/core, it working because they are using a monorepo kind of setup. Here if you add postinstall, it will be run for users trying to install vitepress.

**Comment by zonemeen** [comment]
So now we have to manually execute `npx simple-git-hooks` to make simple-git-hooks take effect. I think it is necessary to remind contributors in the [contributing](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md) file.

**Comment by brc-dd** [comment]
Yeah that would be fine.

**Comment by zonemeen** [comment]
I will submit another PR to remind the rest of the contributors.👀

**Pull request closed without merging**
