### PR TITLE
feat: add component from .components folder

### PR DESCRIPTION
**Pull request by pikax**
Add components from .components folder to the current app.

EDIT: Build not working

### CODE REVIEW

**Comment by posva** [comment]
I'm realizing I created a related PR at #18

**Comment by yyx990803** [comment]
Will have to rebase - also I'm not sure if I'm going to be keeping this feature yet because you can import components from `.md` by adding a `<script/>` tag

**Comment by cloydlau** [comment]
Excuse me, "import components from .md by adding a <script/> tag", how exactly?

**Comment by ismail9k** [comment]
@cloydlau 
This is an example of how to import `TestEl.vue` component in `.md` file

```js
<script>
import TestEl from './components/test-el.vue';

export default {
  components: { TestEl  }
}
</script>
```

**Pull request closed without merging**
