### PR TITLE
perf(style): beautify scrollbar

### PR DESCRIPTION
**Pull request by alex8088**
screenshot

### CODE REVIEW

**Comment by kiaking** [comment]
Hmmmm I don't know, I don't know man. I'm kinda thinking we should keep default styles for this kind of stuff 🤔? It does look good though.

@alex8088 Is that screen shot taken on Windows?

**Comment by alex8088** [comment]
> 



> Hmmmm I don't know, I don't know man. I'm kinda thinking we should keep default styles for this kind of stuff 🤔? It does look good though.
> 
> @alex8088 Is that screen shot taken on Windows?

No, on Ubuntu, a bit blurry. I think it will make the overall visual effect better.

**Comment by meteorlxy** [comment]
As I remember, it will lower the score of a11y (I personally like the style, though)

**Comment by kiaking** [comment]
K let's close this one for now. Personally, I like the style, and thank you for the PR! But I'm still not sure if really want to interact with this kind of thing in terms of a11y and such.

But this might be a cool trick to have as a custom style recipe or something like that 👍

**Pull request closed without merging**
