### PR TITLE
fix: add italic fonts

### PR DESCRIPTION
**Pull request by brc-dd**
fixes: #759

### CODE REVIEW

**Comment by HipyCas** [comment]
When will this come out as a release on NPM?

**Comment by kecrily** [comment]
Is it really necessary to have italic font built in? Why not fallback to other fonts.

**Comment by kecrily** [comment]
Is it really necessary to have italic font built in? Why not fallback to other fonts.

**Comment by brc-dd** [comment]
@kecrily Falling back doesn't appear to be working here. We had `"Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif"` as font family. Setting `font-style: italic` on an element was not using any fallback font and the text was rendering with normal font style.

**Comment by HipyCas** [comment]
When will this be merged???

**Review by kiaking — APPROVED** [review]

**Pull request merged**
