### PR TITLE
fix: custom titles of code snippets inside code groups

### LINKED ISSUE #1785: Can't change title of code snippets inside code groups
### Describe the bug

Seems like it's possible to import code snippets inside code groups, but their titles can't be modified.

### Reproduction

Folder structure:

```
docs/snippets
├── foo.sh
└── bar.sh
```

```
::: code-group

<<< @/snippets/foo.sh

<<< @/snippets/bar.sh [title]

:::

```

image

image

### Expected behavior

image

image

### System Info

```shell
System:
    OS: Linux 6.0 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 7.33 GB / 15.41 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Firefox: 108.0
  npmPackages:
    vitepress: 1.0.0-alpha.36 => 1.0.0-alpha.36
```

### Additional context

Related to https://github.com/vuejs/vitepress/pull/1560#issuecomment-1356501687

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by Raiondesu**
This PR fixes #1785, by allowing the following syntax when a snippet is placed in a code group:

```md
::: code-group

<<< @/snippets/snippet.js [snippet.js]

<!-- with custom tab titles -->
<<< @/snippets/snippet-with-region.js [snippet with region custom title]

<!-- filename is now grabbed by-default -->
<<< @/snippets/snippet.cs{1,2,4-6 c#}

:::
```

See updated docs for an example.

### CODE REVIEW

**Comment by sky124380729** [comment]
when would it be merged, i need this feature

**Comment by Raiondesu** [comment]
@brc-dd, please take a look at this 🙏

It's a small fix, but oh so useful

**Comment by Raiondesu** [comment]
@MarkusKeck, technically the regex doesn't disallow the markup inside the `[title]` brackets, though I didn't test for this.

This PR's code simply passes the parsed title to already existing logic for processing.

**Comment by Raiondesu** [comment]
@MarkusKeck, the regex you mentioned was actually changed to ` ?(?:\[(.+)\])?$` in [this commit](https://github.com/vuejs/vitepress/pull/1834/commits/dedcd4fe1bc8f30a8fcc09e9e885e92c09ce437f)

**Comment by Raiondesu** [comment]
@brc-dd, what's keeping this from being merged?  
Maybe I need to change something in the pr?

**Comment by RaniAgus** [comment]
Thank you! @Raiondesu @brc-dd

**Pull request merged**
