### PR TITLE
feat(client): Config nav support custom target

### LINKED ISSUE #1595: Config nav support custom target
### Is your feature request related to a problem? Please describe.

For example:
The `/docs` is bulit on vitepress, but `/docs/demo` is another project. 
By default, vitepress judge that it is not an external link. It will throw an error when click the nav item:
```js
demo/index.md?import&t=1668047882054  net::ERR_ABORTED 404 (Not Found) 
```
I think it is better to set `target="_blank"`  in such scenarios.

### Describe the solution you'd like

Add a configuration item.
```js
nav: [
  { text: 'NewTab', link: '/newTab', target: '_blank' }
]
```
The custom target has the highest priority.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [ ] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kev1nzh37**
closes #1595

### CODE REVIEW

**Comment by watonyweng** [comment]
Hi @kev1nzh37, i think the value of `target` should be limited to [`_self`, `_blank`, `_parent`, `_top`], please refer to [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) for more information.

**Comment by kev1nzh37** [comment]
> Hi @kev1nzh37, i think the value of `target` should be limited to [`_self`, `_blank`, `_parent`, `_top`], please refer to [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target) for more information.

I have considered this, but will it affect the following situations.

```html
<iframe name="child1" />
<iframe name="child2" />

// vitepress in child1 
<a href="http://www.child1.com/docs1" target="child2">Open</a>
```


Hope to get more suggestions, thanks.

**Comment by brc-dd** [comment]
Allow overriding `rel` too as people might have security concerns.

**Comment by brc-dd** [comment]
Hey, merged this as #1993. Had to rebase due to conflicts.

**Pull request closed without merging**
