### PR TITLE
feat(theme): auto style markdown content in home page

### LINKED ISSUE #800: Markdown Style on the Homepage does not work properly
### Describe the bug

Markdown on the home page does not have the correct article style

image

### Reproduction

```md
---
layout: home

hero:
  name: VuePress
  text: Vite & Vue powered static site generator.
  tagline: Lorem ipsum...
  actions:
    - theme: brand
      text: Get Started
      link: /guide/what-is-vitepress
    - theme: alt
      text: View on GitHub
      link: https://github.com/vuejs/vitepress

features:
  - icon: ⚡️
    title: Vite, The DX that can't be beat
    details: Lorem ipsum...
  - icon: 🖖
    title: Power of Vue meets Markdown
    details: Lorem ipsum...
  - icon: 🛠️
    title: Simple and minimal, always
    details: Lorem ipsum...
---

# H1
hello world
## H2
hello world
### H3
hello world

```sh
npm i -g vitepress
\```
```

### Expected behavior

HomePage markdown have the right Style  Like docs

image

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 716.61 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 102.0.5005.115
    Edge: 102.0.1245.41
    Safari: 14.0.3
  npmPackages:
    vitepress: ^1.0.0-alpha.2 => 1.0.0-alpha.2
```

### Additional context

image

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by jcbhmr**
fix #800 using https://github.com/vuejs/vitepress/issues/800#issuecomment-1594473590 code

### CODE REVIEW

**Comment by jcbhmr** [comment]
<details><summary>If you're using pnpm here's a <code>.patch</code> file that you can use to apply this change to vitepress on <code>pnpm install</code></summary>

`package.json`
```json
{
  "pnpm": {
    "patchedDependencies": {
      "vitepress@1.0.0-rc.42": "patches/vitepress@1.0.0-rc.42.patch"
    }
  }
}
```

`patches/vitepress@1.0.0-rc.42.patch`
```diff
diff --git a/dist/client/theme-default/components/VPHome.vue b/dist/client/theme-default/components/VPHome.vue
index d69a79b21a734adfc6253c74c32ed400fa25eb1f..a5aedb0855ad134bd3d91a18afc78dc2fd027aed 100644
--- a/dist/client/theme-default/components/VPHome.vue
+++ b/dist/client/theme-default/components/VPHome.vue
@@ -1,6 +1,7 @@
 <script setup lang="ts">
 import VPHomeHero from './VPHomeHero.vue'
 import VPHomeFeatures from './VPHomeFeatures.vue'
+import VPHomeContent from './VPHomeContent.vue'
 </script>
 
 <template>
@@ -19,7 +20,9 @@ import VPHomeFeatures from './VPHomeFeatures.vue'
     <VPHomeFeatures />
     <slot name="home-features-after" />
 
-    <Content />
+    <VPHomeContent>
+      <Content />
+    </VPHomeContent>
   </div>
 </template>
 
diff --git a/dist/client/theme-default/components/VPHomeContent.vue b/dist/client/theme-default/components/VPHomeContent.vue
new file mode 100644
index 0000000000000000000000000000000000000000..2b735857f88dd398b5eda0f25f65684199303b8a
--- /dev/null
+++ b/dist/client/theme-default/components/VPHomeContent.vue
@@ -0,0 +1,25 @@
+<template>
+  <div class="vp-doc container">
+    <slot />
+  </div>
+</template>
+
+<style scoped>
+.container {
+  margin: auto;
+  width: 100%;
+  max-width: 1280px;
+  padding: 0 24px;
+}
+@media (min-width: 640px) {
+  .container {
+    padding: 0 48px;
+  }
+}
+@media (min-width: 960px) {
+  .container {
+    width: 100%;
+    padding: 0 64px;
+  }
+}
+</style>
```

</details>

**Comment by jcbhmr** [comment]
To clarify: the end goal is to be able to do this **WITHOUT MUCH CONFIG** importing any additional components. (no `import VPHomeContent from "vitepress/somewhere"` in a `<script>` tag needed)

````md
layout: home
docsOnHomepage: true # or "extraHomeContent: true" or whatever

hero: ...
---

You can get started using $X right away! You can use npm, Yarn, pnpm, or bun to install it:
```sh
npm install $X
```

Read more in [the getting started guide](/guide/)
````

an option could be added if this absolutely cannot be default behavior 🤷‍♀️ similar to how there's a `pageClass: my-custom-page-class` that can be added as a frontmatter option. imo tho this shouldnt require importing something or wrapping it in some weird sorcery component just to fix formatting on the homepage.

**Comment by brc-dd** [comment]
Yeah we can go with frontmatter approach. It'll just need a v-if.

**Comment by jcbhmr** [comment]
`homeDocs: <anything|unspecified>` enables the new normal Markdown styles
`homeDocs: false` disables the normal Markdown styles and just plops the `<Content />` in there as before (old behaviour)

Added this to the docs:
image

**Comment by Swivelgames** [comment]
We're rapidly approach the point of no return on this.

It seems appropriate to have it on by default, but I agree that **_this is a breaking change._** It's not too late to make this change, and I still feel strongly that this was a gross oversight to leave out initially but, unless this gets prioritized ASAP, we're going to rapidly approach the point that `off by default` is the only path forward.

**Comment by brc-dd** [comment]
Yeah I'll merge and release this by weekend.

**Comment by brc-dd** [comment]
nb, level 1 headings (`# Foo`) are not supported as they don't look good with hero section in place. Also, hero section already adds `hero.name` as `<h1>`, and keeping multiple level 1 headings in same page is discouraged. Use level 2 or more (`## Foo`). If one still wants to keep level 1 heading as adjacent sibling to hero / features section, they will need to add custom CSS to adjust margin, etc.

**Pull request merged**
