### PR TITLE
fix: Chinese file link build failed (#424)

### PR DESCRIPTION
**Pull request by fuchunhui**

### CODE REVIEW

**Comment by Xu-pixel** [comment]
but in v0.22.3, it is still not work.
image

**Comment by fuchunhui** [comment]
Just tried this and didn't reproduce your problem. you can [try here](https://github.com/fuchunhui/test-vitepress)
I guess that the possible reason is the path problem of your file.

Here are some tips:
* Ask questions needed in the issue area.
* Provide to a demo that can be reproduced so that others can help you solve it more quickly.
* More detailed description of the problem, step by step.

Demo for you.
image

**Comment by Xu-pixel** [comment]
Thank you for your reply.It can work well in dev environment but error in build.

I downloaded your project and used yarn docs:build:
image

**Comment by Xu-pixel** [comment]
Thank you !

**Pull request merged**
