### PR TITLE
docs: keyword vuepress change vitepress

### PR DESCRIPTION
**Pull request by qdbest**
This should be vitepress.

### CODE REVIEW

**Comment by antfu** [comment]
I guess this was intended? Maybe instead of replacing, we can append "vitepress" to the list

**Comment by qdbest** [comment]
I guess that it was copied from the project of vuepress, but was forgot to modify.

**Comment by qdbest** [comment]
There are two mistakes in the file markdown.md.

**Comment by antfu** [comment]
Don't feel the change to highlight.ts is necessary, reverted and merging the rest. Thanks

**Pull request merged**
