### PR TITLE
fix: `createContentLoader` generates invalid url when sets `srcDir`

### PR DESCRIPTION
**Pull request by zonemeen**
closes https://github.com/vuejs/vitepress/issues/2540 
closes https://github.com/vuejs/vitepress/issues/2462

### CODE REVIEW

**Comment by brc-dd** [comment]
I'll get back on this. Need to check on some projects as this will be a breaking change. Seems right though.

**Comment by SapneshNaik** [comment]
@ brc-dd, when will this be merged? This is causing a weird issue where the logo is no longer showing if I set a custom `srcDir` rather leaving it blank as it comes by default.

**Comment by brc-dd** [comment]
What does this have to do with logo?

**Comment by SapneshNaik** [comment]
@brc-dd the Logo URL (set in the `themeconfig` ) breaks if you set a different source dir using the `srcDir` config option.

**Comment by brc-dd** [comment]
@SapneshNaik That isn't related to this PR. Please create a separate issue for that.

**Comment by domnantas** [comment]
Agree that this change makes sense, I don't see any reason for `createContentLoader` to have access outside `srcDir`. Docs would need to be updated here too https://vitepress.dev/guide/data-loading#createcontentloader

**Pull request merged**
