### PR TITLE
feat(theme): new design for local nav and global header

### LINKED ISSUE #2751: 🎨 Improve navbar blur styles
### Is your feature request related to a problem? Please describe.

Hi 👋🏻 

We are now moving towards v1 and with the merge of #2727 I would like to purpose another change which makes VitePress more elegant.

ATM, navbar blur on scroll doesn't blend into the content purticularly when it's dark content like code block
image

If you notices there's thick line clearly separating the navbar and the content.

### Describe the solution you'd like

Making it more smoother. I don't have words for this but I guess you know how it should look.

### Describe alternatives you've considered

None

### Additional context

none

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by kiaking**
- close #2751

A new styles for outline dropdown on tablet viewport. This PR also adds new composable `useLocalNav` to check if the local nav is there.

This removes the blurred header "curtain" and simply adds divider between header and the content.

Screenshot 2023-12-19 at 23 47 33

Screenshot 2023-12-19 at 23 47 45

Screenshot 2023-12-19 at 23 47 48

Screenshot 2023-12-19 at 23 47 56

Screenshot 2023-12-19 at 23 49 20

### CODE REVIEW

**Comment by brc-dd** [comment]
Some transition duration is wrong. Try resizing browser window to lower height and scroll the home page up and down, that logo-side divider seems to have no transition.

**Comment by kiaking** [comment]
@brc-dd 
Nice catch. Thanks. Fixed. The divider container was having wrong padding 👀

**Comment by brc-dd** [comment]
z-index issue?

image

**Comment by kiaking** [comment]
Oh no... thanks for spotting. Yeah the z-index is a bit of mess. I'll stop being lazy and reorganize them.

**Comment by kiaking** [comment]
@brc-dd 
I think I've fixed it!

**Comment by brc-dd** [comment]
LGTM. I'll make some changes to handle body scroll and closing on esc/click outside.

**Pull request merged**
