### PR TITLE
✨ feat: add hero slots that are inside container

### PR DESCRIPTION
**Pull request by jd-solanki**
Hi 👋🏻 

When trying to add some content before app title & after actions **but inside container** there's no easy way, we have to create custom container class and VitePress' container classes are also scoped which we can't leverage.

Basically, What I'm trying to create is something like this:
image

> _P.S. There's no need for `home-hero-actions-before` because `home-hero-info-after` can do the job_

### CODE REVIEW

**Comment by jd-solanki** [comment]
If possible can you please let me know when you are planning for new release because I'm going to release Vue Cheatsheet based on VitePress today so I can decide if I should have to wait or not.

**Review by brc-dd — APPROVED** [review]

**Comment by brc-dd** [comment]
> you are planning for new release

Most likely by this weekend. I'm waiting on some other libraries to release patches. Hopefully that will be the last/second to last RC.

**Comment by pirog** [comment]
@jd-solanki @brc-dd wouldn't it make sense to also bubble these slots up to at least VPHomeHero.vue since that is the component that is actually exported with the theme?

**Comment by brc-dd** [comment]
Yeah right. I'll update that.

**Pull request merged**
