### PR TITLE
fix(theme): nav bar overflowed by aside when no sidebar

### LINKED ISSUE #2442: Outline overflows navbar when sidebar not present
### Describe the bug

When sidebar is not present, the page is not scrolled and outline is scrolled down, it overflows the navbar.

 
img

### Reproduction

https://stackblitz.com/edit/vite-v81ufa

1. Make sure width is high enough so that outline is shown
2. Without scrolling the main page content hover over the outline and scroll down
3. Observe that the outline overflows the navbar

### Expected behavior

Outline is clipped when over navbar in the same way when sidebar is present.

### System Info

```sh
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-6900K CPU @ 3.20GHz
    Memory: 45.66 GB / 63.92 GB
  Binaries:
    Node: 18.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 113.0.5672.127
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.50)
  npmPackages:
    vitepress: ^1.0.0-beta.1 => 1.0.0-beta.1
```

### Additional context

_No response_

### Validations

- [X] Check if you're on the [latest VitePress version](https://github.com/vuejs/vitepress/releases/latest).
- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by Elringus**
Fixes #2442 

Not sure if I've exposed aside scroll ref correctly, as I'm dealing with vue for the first time. Please let me know if this should be implemented differently.

### CODE REVIEW

**Comment by zonemeen** [comment]
Please check and submit again, because the CI did not pass.

**Comment by Elringus** [comment]
> Hi @Elringus , Please check and submit again, because the CI did not pass.

My bad, forgot to run formatter. Should be ok now.

**Comment by zonemeen** [comment]
The issue is still there. When I first click into the corresponding page from the home page, the background transparency is still there when I scroll the right side outline.

GIF 2023-6-1 18-08-13

**Comment by Elringus** [comment]
> The issue is still there. When I first click into the corresponding page from the home page, the background transparency is still there when I scroll the right side outline.
> 

Weird. Works fine on my end (testing with `pnpm run docs`).

https://github.com/vuejs/vitepress/assets/2056864/25511468-649b-45b8-9824-ef7ea5ad8a5d

**Comment by Elringus** [comment]
Got it. `document.querySelector('.aside-container')` returns null when invoked under `onMounted()` of "aside" when navigating from the home page. At the same time it's resolved correctly when navigating from any other page. I'm not familiar with vue components lifetime; any suggestions on how to retrieve the container properly?

**Comment by Elringus** [comment]
Guess it's a hack, but I've added the listen hook to onUpdated as well, which seems to be invoked when navigating from home (though it's not invoked when navigating from other pages, so onMounted is used as well). Now it's working when navigating from any page.

**Comment by Elringus** [comment]
https://github.com/vuejs/vitepress/issues/2442#issuecomment-1574134970

**Pull request closed without merging**
