### PR TITLE
refactor: simplify the import path

### PR DESCRIPTION
**Pull request by zonemeen**

### CODE REVIEW

**Comment by brc-dd** [comment]
Hey a suggestion here, don't do merge. Use "squash and merge" option instead. That way master can have linear history.

**Comment by zonemeen** [comment]
Ok, sorry about that. Thanks for the suggestion.

**Comment by zonemeen** [comment]
Does this need to reset?

**Comment by brc-dd** [comment]
Nah leave it.  No need to revert. Just remember to do squash next time.

**Pull request merged**
