### PR TITLE
feat(theme): add appearance transition feature

### PR DESCRIPTION
**Pull request by hooray**
Use [View Transition API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) to make appearance switch more dynamic.

Kapture 2023-05-07 at 05 36 16

But these APIs needs Chrome 111, so I added a configuration item `appearanceTransition` that can be selectively enabled.

### CODE REVIEW

**Comment by hooray** [comment]
> Brilliant idea! I posted it on Twitter to collect feedback: [twitter.com/antfu7/status/1655588888105172994](https://twitter.com/antfu7/status/1655588888105172994)
> 
> Do you think we could enable `appearanceTransition` in this PR so we could play with it with the deploy preview?

Of course

**Comment by brc-dd** [comment]
Might wanna consider some other factors too:

- Disable this on `prefers-reduced-motion`
- Maybe decrease the duration to something like 200 or 300. Currently, it seems slightly slow to me 👀

**Comment by hooray** [comment]
> Might wanna consider some other factors too:
> 
> * Disable this on `prefers-reduced-motion`
> * Maybe decrease the duration to something like 200 or 300. Currently, it seems slightly slow to me 👀

I made some adjustments based on your suggestions

**Comment by antfu** [comment]
Playing it on antfu.me, a few feedback

- I feel it's better to reverse the out/in animation for light/dark. Making the light icon more like a "sun" to light up the canvas. (already applied to https://antfu.me/ that you can play with)
- The animation is not very smooth, especially with low `duration` on a large screen (tho the FPS stays consistent according to Chrome DevTools). I am not sure if this is something we could improve. Maybe we can change the duration based on distance?

**Comment by kiaking** [comment]
This is very cool and I'm surprised how simple it's to implement 😳  Well done!

However, my personal opinion is I'm against adding this to the core feature. Love to see this as some kind of plugin feature or recipe. Or tweak the core code to make VitePress easy to implement this effect.

The reason why I'm against adding this specific animation effect in the core 😓 

1. The growing circle animation I don't think is aligned with Vue or Vite tone.
2. Without having disciplined brand guideline, this kind of animation will almost certainly look cool at first but become off trend and not that cool very very quickly (do you remember what happened to polygon design trend).
3. If we add this, there's no turning back. If we undo or change the effect, some forks would not like it.
4. If we add this, I'm pretty sure we'll gets requests to add different types of effect (crossfade, slides, etc.). I don't think VitePress core wants to focus so much on animation effects.

That's been said and as I mentioned, it would be super cool if default theme has a cool way for users to hook in this kind of animation 👍

**Comment by yuhengshen** [comment]
speed up the transition and simplify `[...clipPath].reverse()` to `clipPath.reverse()`

**Comment by hooray** [comment]
> This is very cool and I'm surprised how simple it's to implement 😳 Well done!
> 
> However, my personal opinion is I'm against adding this to the core feature. Love to see this as some kind of plugin feature or recipe. Or tweak the core code to make VitePress easy to implement this effect.
> 
> The reason why I'm against adding this specific animation effect in the core 😓
> 
> 1. The growing circle animation I don't think is aligned with Vue or Vite tone.
> 2. Without having disciplined brand guideline, this kind of animation will almost certainly look cool at first but become off trend and not that cool very very quickly (do you remember what happened to polygon design trend).
> 3. If we add this, there's no turning back. If we undo or change the effect, some forks would not like it.
> 4. If we add this, I'm pretty sure we'll gets requests to add different types of effect (crossfade, slides, etc.). I don't think VitePress core wants to focus so much on animation effects.
> 
> That's been said and as I mentioned, it would be super cool if default theme has a cool way for users to hook in this kind of animation 👍

It makes sense, I think I need to think about whether to continue this PR 🤔

**Comment by yuhengshen** [comment]
@brc-dd Every clipPath is a new array, so it’s okay to mutate the original array directly.

**Comment by AgustinBanchio** [comment]
Would like to have a look into this as I would like this feature.

Do you think the most acceptable solution would be:

A. Passing a transition function through the themeConfig and handling it in VPSwitchAppearance in a way similar to this PR? (which also modifies the component to look different if a transition exists and is possible)
B. Allowing users to replace VPSiwtchAppearance with a custom component that has access to a version of `toggle` or `setClass` and they are free to wrap those around anything they want (including transitions and or having a different toggle look?

I feel like option B is more of a custom theme solution, so think option A is more likely to make sense

**Pull request closed without merging**
