### PR TITLE
feat: add code-group component

### LINKED ISSUE #728: Support code groups and allow adding title to code blocks
### Is your feature request related to a problem? Please describe.

VueJS community is moving from JS to TS now. Hence, we have to provide both TS & JS code.

I already started using VitePress alpha in my OSS project but for another project, I prefer providing TS & JS code via code groups like VuePress.

### Describe the solution you'd like

Provide code blocks via markdown (using component is bit ugly for markdown only content). We can inspire from Nuxt content 2 for new syntax

<pre>
:::code group

:::group{ts}

```ts
const a: number = 1
```

:::

:::group{js}

```js
const a = 1
```

:::

:::
</pre>

### Describe alternatives you've considered

None

### Additional context

https://content.nuxtjs.org/guide/writing/mdc

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by brc-dd**
fixes #728
closes #1242

Huge thanks to @VoVAllen!

TODO:
- [x] Add docs
- [ ] Remove /test
- [ ] Check something like #1594 isn't happening.

### CODE REVIEW

**Comment by VoVAllen** [comment]
image
The width of header looks a bit weird

**Comment by brc-dd** [comment]
I've actually took most of the UI from what we have in @vue/theme ([a demo is here](https://vuejs.org/guide/scaling-up/testing.html#component-testing)).

/cc @kiaking Your inputs? Should we change the UI?

**Comment by kiaking** [comment]
@brc-dd yeah I'll take this one over! I would like to adjust a just bit on tabs 👀 I'll work this on today or tomorrow 👍

**Comment by jd-solanki** [comment]
My thoughts on UI: https://github.com/vuejs/vitepress/issues/728#issuecomment-1296586489

**Comment by mancuoj** [comment]
Wow! Will this feature appear in the next release? So I don't have to use the garbage code I wrote 👀

**Comment by kiaking** [comment]
Hopefully! Sorry it's taking time but I will work on it.

**Comment by kiaking** [comment]
OK finally! I've modified the style to be:

Screenshot 2022-12-16 at 0 10 37

Screenshot 2022-12-16 at 0 10 30

**Review by kiaking — APPROVED** [review]

**Comment by jd-solanki** [comment]
I love this style 😍

**Comment by VoVAllen** [comment]
Glad to see this feature got merged!

**Comment by dmoyadev** [comment]
I have the same problem with this feature as @MarkusKeck, code snippets are not working and I think it is a core feature with large code blocks or change-prone ones, is there a workaround or something to have them working? Thanks in advance!

**Pull request merged**
