### PR TITLE
fix(next): scroll to anchor (#653)

### PR DESCRIPTION
**Pull request by RainKolwa**

### CODE REVIEW

**Comment by brc-dd** [comment]
Hi. Thanks for the PR. But can you explain what's being done here? i.e. what was wrong with `nextTick`?

**Comment by kiaking** [comment]
So, what is not working here? Scroll to anchor is working, isn't it? 🤔 Could you discribe what issue you're facing at the moment?

**Comment by RainKolwa** [comment]
This PR fixes #653 .

**Comment by RainKolwa** [comment]
I did some test like:
```js
setTimeout(() => console.log(document.querySelector('#app').innerHTML));
nextTick(() => console.log(document.querySelector('#app').innerHTML));
```
and it turned out that the `nextTick` line just printed empty, whereas `setTimeout` works.

**Comment by kiaking** [comment]
Hmmm, strange. I'm not sure if I like ``setTimeout being used here. Though I don't have any other way of doing it, but... At least is's working on Prod env, I would like to know bit more on why this issue is happening.

**Pull request closed without merging**
