### PR TITLE
docs: port deploy instructions for common services from vuepress

### PR DESCRIPTION
**Pull request by matias-capeletto**
Port deploying to common services mini-tutorials from vuepress: https://vuepress.vuejs.org/guide/deploy.html

Deploying works the same way, so not much to change except for vuepress -> vitepress

The only modified section is Vercel, because for vuepress it is pointing to a post in vercel.com. I extracted the deploying guide from that post and included a picture of the wizard base configuration process.

Note: I did not test these instructions in all the platforms, but I assume the docs in vuepress are up to date in this regard.

### CODE REVIEW

**Review by kiaking — CHANGES_REQUESTED** [review]
Nice work! For the GitHub deploy, could you add instruction to place `.nojekyll` file in `public` folder. Regarding https://github.com/vuejs/vitepress/issues/124#issuecomment-727821279.

Then I guess we can close #124 by this PR 😳

**Comment by matias-capeletto** [comment]
Ok, I'll add this later 👍 

Are there benefits to use `_assets` instead of `assets` like VuePress does and you proposed in that issue? Because If not, maybe we should change that so users do not trip with this (a lot of people will not read that part of the docs for sure)

**Comment by kiaking** [comment]
I think `_assets` thing is coming from Vite (need to double check). And there's technically nothing wrong with having underscore in URL. It's more of GitHub page issue really.

But, yes, this will trip lots of users, so we might wanna add `.nojekyll` to the `dist` folder on build time. Hmmm... ok let's not close #124 with this issue, and let's provide some feasible solution.

**Comment by matias-capeletto** [comment]
Ok, I added a temporal warning in the mean time as you proposed.

**Review by kiaking — APPROVED** [review]

**Pull request merged**
