### PR TITLE
docs: add Persian language

### LINKED ISSUE #4047: Add Persian Language to the Documentation
### Is your feature request related to a problem? Please describe.

As a native Persian speaker and a developer who frequently uses VitePress, I often find myself frustrated by the lack of Persian language documentation. This can be a barrier for Persian-speaking developers who might not be fluent in English, making it difficult to fully utilize and contribute to the VitePress project.

### Describe the solution you'd like

I would like to contribute to the VitePress documentation by adding a Persian language option. This would involve translating the existing documentation into Persian and ensuring that all future updates are also translated. This addition would make the documentation more accessible to Persian-speaking developers, thereby fostering a more inclusive and diverse community.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by amir78729**
### Description

This PR adds the Persian language locale to VItePress Doc

### Linked Issues

fixes #4047 

### Additional Context

-

---

> [!TIP]
> The author of this PR can publish a _preview release_ by commenting `/publish` below.

### CODE REVIEW

**Comment by brc-dd** [comment]
Please update lunaria.json too. And I need someone from the community to review the translations. I also need feedback on RTL UI. Let me know which things look weird and how they should look, I will adjust the styles.

**Comment by userquin** [comment]
@brc-dd maybe this can help you (or not ;) ): https://github.com/elk-zone/elk/blob/main/CONTRIBUTING.md#rtl-support

**Comment by amir78729** [comment]
@brc-dd  Are there any updates on fixing RTL issues? Is there anything I can help with?

**Comment by brc-dd** [comment]
Ah, sorry, no. I'm bit busy recently with day job. Will try to look into by next week.

**Comment by amir78729** [comment]
> Ah, sorry, no. I'm bit busy recently with day job. Will try to look into by next week.

No problem. Let me know if there's anything I can help you with.

**Comment by amir78729** [comment]
Any updates? @brc-dd

**Comment by amir78729** [comment]
Any updates? @brc-dd

**Comment by amir78729** [comment]
Any updates? @brc-dd

**Comment by brc-dd** [comment]
Sorry for the delay.

Can you check [the preview](https://deploy-preview-4089--vitepress-docs.netlify.app/) again and list out the issues? (The language picker still has ltr<>rtl issues, I'll update the code.)

Also, the individual headings need anchors, so that switching locales can keep the position same. See https://github.com/vuejs/vitepress/blob/main/docs/ru/guide/asset-handling.md?plain=1 for example (notice things inside `{...}`)

**Comment by amir78729** [comment]
> Sorry for the delay.
> 
> Can you check [the preview](https://deploy-preview-4089--vitepress-docs.netlify.app/) again and list out the issues?
> 
> Also, the individual headings need anchors, so that switching locales can keep the position same. See https://github.com/vuejs/vitepress/blob/main/docs/ru/guide/asset-handling.md?plain=1 for example (notice things inside `{...}`)

Everything looks fine.

There's another thing that I suggest changing. If the text color has opacity in languages like Persian (where the characters are connected), the overlap of characters will be bolder. Can we remove the opacity and use solid text colors to avoid the bolder overlap of characters?


image

**Comment by userquin** [comment]
external link icons shouldn't be changed with `transform: rotate(-90deg)`?

imagen

**Comment by brc-dd** [comment]
updated

**Pull request merged**
