### PR TITLE
fix: check base before redirecting to .html

### PR DESCRIPTION
**Pull request by JounQin**
closse #852

### CODE REVIEW

**Comment by JounQin** [comment]
For `base: '/docs/'`, there can't be a `/docs.html` file.

**Comment by JounQin** [comment]
cc @brc-dd

**Comment by brc-dd** [comment]
Hi! I'm aware of this PR. But will have to discuss this first with others.

**Comment by JounQin** [comment]
> Hi! I'm aware of this PR. But will have to discuss this first with others.

Yeah, of course.

**Pull request closed without merging**
