### PR TITLE
fix: support symbolic links in building docs dist (#184)

### LINKED ISSUE #184: Build doesn't support symbolic links
**Describe the bug**
In dev mode symbolic links work just fine but building process fails with following errors:
```
$ vitepress build docs
vitepress v0.9.2
vite v1.0.0-rc.13
✓ building client + server bundles...
✖ rendering pages...
build error:
 TypeError: Cannot read property 'imports' of undefined
    at resolvePageImports (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/render.js:74:68)
    at Object.renderPage (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/render.js:35:12)
    at async Object.build (/home/lromanowicz/projects/vitepress-issues/node_modules/vitepress/dist/node/build/build.js:29:17)
error Command failed with exit code 1.
```

**To Reproduce**
* add a directory with docs through a symbolic link

https://github.com/lukeromanowicz/vitepress-issues/tree/issue/building-not-supporting-symbolic-links

**Expected behavior**
Building supports symbolic links just like dev mode does.

**System Info**
- vitepress version: 0.9.2
- vite version: 1.0.0-rc.13 
- Node version: 14LTS
- OS version: Ubuntu 20

### PR DESCRIPTION
**Pull request by lukeromanowicz**
This PR fixes error when building docs that contain symbolic links. Results.assets have links resolved to the real files while srcPath was ignoring if the path was a symbolic link.

The performance seems to be intact (upper execution before the fix, bottom execution after the fix)
image

Closes #184

### CODE REVIEW

**Comment by lukeromanowicz** [comment]
@posva @kiaking Please, review 🙏

**Review by posva — CHANGES_REQUESTED** [review]
can you solve the merge conflicts?

**Comment by lukeromanowicz** [comment]
> can you solve the merge conflicts?

I'm not sure what to fix, I don't see any conflicts:
image

**Comment by kiaking** [comment]
Thanks a lot on the PR! 🙌

**Pull request merged**
