### PR TITLE
feat(client): support homepages feature

### PR DESCRIPTION
**Pull request by kazupon**
vitepress-homepages

### CODE REVIEW

**Comment by kazupon** [comment]
Custom layouting with slots
vitepress-homepages2

**Comment by kazupon** [comment]
Please don't merge the PR.
I've found the bug.
This PR doesn't work when `sidebar` has an object setting.

**Comment by kazupon** [comment]
@kiaking 
I've fixed the bug with [this](https://github.com/vuejs/vitepress/pull/108/commits/284c16687e251f7073ac17bc6875087c1ee5af4e) commit.

Please review this PR! 👍

**Review by kiaking — APPROVED** [review]
Checked at my environment too. Working great! Thank you so much 🙌

**Pull request merged**
