### PR TITLE
feat(theme): add --vt-layout-top-height to adjust banner

### PR DESCRIPTION
**Pull request by ylw5**
https://github.com/vuejs/vitepress/issues/1497#issue-1411582926
Add Banner to layout-top slot similar to @vue/theme.
```
// .vitepress/theme/index.ts

export default {
  ...DefaultTheme,
  Layout() {
    return h(DefaultTheme.Layout, null, {
      'layout-top': () => h(Banner)
    })
  }
}
```
```
// Banner.vue

<template>
  <div class="banner">
    banner
  </div>
</template>

<style>
html{
  --vp-layout-top-height: 30px;
}
</style>

<style scoped>
.banner {
  position: fixed;
  z-index:var(--vp-z-index-layout-top);
  top: 0;
  left: 0;
  right: 0;
  height: var(--vp-layout-top-height);
  background: -webkit-linear-gradient(315deg, #96c93c 25%, #03b19a);
}
</style>
```

### CODE REVIEW

**Comment by ylw5** [comment]
#1497

**Comment by brc-dd** [comment]
Make it `--vp-` instead of `--vt-`.

**Comment by brc-dd** [comment]
Thanks! 🎉

**Comment by ylw5** [comment]
Thanks for your review!

**Comment by VedxP** [comment]
> Thanks for your review!

Would it be documented any soon, sir?

**Comment by ylw5** [comment]
> Would it be documented any soon, sir?

I don't know if it is necessary to add description of layout-top to document.

**Pull request merged**
