### PR TITLE
feat: allow using components in navigation bar

### LINKED ISSUE #3998: Allow use components inside navbar
### Is your feature request related to a problem? Please describe.

Add a new option to `DefaultTheme.NavItem` to allow use a component.

I'll try to send a PR tmr.

/cc @brc-dd 

### Describe the solution you'd like

Replace the content via `component::is`

### Describe alternatives you've considered

None

### Additional context

Check https://github.com/unocss/unocss/pull/3931

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.dev).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by userquin**
✔️  I  need to add an example/test...

closes #3998

### CODE REVIEW

**Comment by userquin** [comment]
we should also add fly, maybe includng `mode` type: `type Mode = 'screen' | 'fly' | undefined`  or `type Mode = 'screen' | 'fly' | 'navbar'`

**Comment by userquin** [comment]
@brc-dd same component in multiples places, no makes sense, do we need the new mode prop?  maybe not, since we should always have screen in screen menu (we'll need to add screen prop when custom component in root)

fly-screen-navbar

fly-screen-navbar-2

**Comment by brc-dd** [comment]
Do we need some option to move component to flyout in medium viewports? Inside this thing:

image

**Comment by userquin** [comment]
I guess there is no need, `fly` will be used when the custom component is not a root child in the navbar entry. If the custom component is in the root navbar, VP will not use `fly` (will use media query bp to collapse or expand the full navbar)

**Review by brc-dd — APPROVED** [review]

**Pull request merged**
