### PR TITLE
feat(theme): support links in homepage features (#984)

### PR DESCRIPTION
**Pull request by Jimmylxue**
Now, the features configuration on the home page is very beautiful, but sometimes we need to be able to jump to the specified articles for some features。

just like actions config on the home page, now just need to add "link" config that we can jump to other page。

## The configuration is modified as follows

```
---
layout: home

features:
  - icon: ⚡️
    title: vitepress
    details: hello world
    link: https://github.com/vuejs/vitepress
  - icon: 🖖
    title: vue
    details: Thanks for checking
  - icon: 🛠️
    title: TypeScript
    details:Thanks for checking
    link: https://github.com/vuejs/vitepress
---
```

> Link is an optional configuration. It remains unchanged by default when it is not configured

### CODE REVIEW

**Comment by brc-dd** [comment]
I suppose we need either this or #1070. Let Kia decide what's best. The difference between these is this PR makes whole feature a link, while the other PR adds a button in it.

**Comment by Jimmylxue** [comment]
fine~，I didn't know that pr existed。
I just think it is necessary. I added links and corresponding effect animations to the whole body, not through buttons.
Thank you for your reply。

**Comment by yuetaibai** [comment]
Link for the homepage is very useful feature, when could it be merged into dev version, please update the progress, wait for use, thanks

**Comment by kiaking** [comment]
Yes, I'll take this over. Sorry for the delay!

**Comment by kiaking** [comment]
I've updated the design, and also added `linkText` feature too 🚀 

Screen Shot 2022-10-31 at 18 31 24

**Comment by Jimmylxue** [comment]
> I've updated the design, and also added `linkText` feature too 🚀
> 
> Screen Shot 2022-10-31 at 18 31 24

that's awesome!

**Comment by yuetaibai** [comment]
Great, thanks for the update !

**Pull request merged**
