### PR TITLE
fix: decode href before using as query selector

### LINKED ISSUE #950: If the `VPDocAsideOutline` switch is in Chinese, the parsing will be wrong
### Describe the bug

If the `VPDocAsideOutline` switch is in Chinese, the parsing will be wrong

### Reproduction

图片

### Expected behavior

Hope to switch normally, thank you

### System Info

```shell
browsers
  System:
    OS: macOS 12.4
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 103.0.5060.114
    Firefox: 102.0
    Safari: 15.5
```
```


### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by brc-dd**
fixes #950

### CODE REVIEW

**Comment by gyhyfj** [comment]
Could  it work  if the `h2` title start with special char?  
Such as`+` `-`

**Comment by brc-dd** [comment]
@gyhyfj Is it not working?

**Comment by gyhyfj** [comment]
> @gyhyfj Is it not working?
It doesn't work well at "vitepress": "^1.0.0-alpha.1".
Like this link :
https://www.gyhyfj.com/code/html-css-js/es/%E8%BF%90%E7%AE%97.html#-4
If I click the the toc in `.VPDocAsideOutline`  , on the right side of the web, 
the page can't scroll to the right place as usual

**Comment by gyhyfj** [comment]
It doesn't work well at "vitepress": "^1.0.0-alpha.1".
For example:
[example page](https://www.gyhyfj.com/code/html-css-js/es/%E8%BF%90%E7%AE%97.html)
The md file is like this:
```md
# Reading
...
... 
## `- + * /`
...
...
```

If I click toc in `.VPDocAsideOutline` , on the right side of the web,
the page can't scroll to the right place as usual.
Chrome terminal report :
```js
DOMException: Failed to execute 'querySelector' on 'Document': '#-5' is not a valid selector.
    at c (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:124560)
    at $t (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:12734)
    at qe (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:12813)
    at HTMLAnchorElement.n (https://www.gyhyfj.com/assets/app.4bd937d4.js:1:56875)
```

**Comment by brc-dd** [comment]
Hey can you create a seperate issue for this one. It's probably because we cannot auto generate an id from that heading. You can try something like

```
## `- + * /` {#foo}
```

**Pull request merged**
