### PR TITLE
docs(zh): add translations for zh-CN

### LINKED ISSUE #1285: Chinese Version Document
### Is your feature request related to a problem? Please describe.

希望官方能出一套中文的文档，感谢

### Describe the solution you'd like

希望官方能出一套中文的文档，感谢

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Validations

- [X] Follow our [Code of Conduct](https://vuejs.org/about/coc.html)
- [X] Read the [docs](https://vitepress.vuejs.org).
- [X] Read the [Contributing Guidelines](https://github.com/vuejs/vitepress/blob/main/.github/contributing.md).
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.

### PR DESCRIPTION
**Pull request by awxiaoxian2020**
close #1285.

You can preview it at https://deploy-preview-2249--vitepress-docs.netlify.app/zh/

It will be ready for review after:

- [x] #1339 merged. 
- [x] complete the translations and configs.

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
A rough translation completed. I will update the configs for i18n and polish the translations after #1339 merged.

I reference some contents in https://github.com/process1024/vitepress . Thanks for @process1024 and the people who are contributed to the translations!

**Comment by awxiaoxian2020** [comment]
Who can help with the CI...

**Comment by awxiaoxian2020** [comment]
@brc-dd How do you think the VitePress i18n docs config structure should be better?

**Comment by brc-dd** [comment]
Add zh directory, keep english one on the root. This way it won't break the URLs.

**Comment by awxiaoxian2020** [comment]
> Add zh directory, keep english one on the root. This way it won't break the URLs.

What I said is **config** like `nav`.  Where should I add `zh` nav?

**Comment by brc-dd** [comment]
Ah okay. You can create a config directory and create two files (en.ts and zh.ts). and merge/reexport them from config/index.ts. It would be cleaner that way.

**Comment by awxiaoxian2020** [comment]
Welcome to review!

**Comment by awxiaoxian2020** [comment]
@brc-dd Could we add a netlify bot for previewing directly like [this](https://github.com/vuejs/pinia/pull/1911/#issuecomment-1368600165)?

**Comment by brc-dd** [comment]
Deploy previews are already enabled. Just the bot isn't added to prevent noise. One can open the deploy preview like this:

image

(Click on details aside deploy/netlify.)

**Comment by awxiaoxian2020** [comment]
> Deploy previews are already enabled. Just the bot isn't added to prevent noise. One can open the deploy preview like this:
> 
> image
> 
> (Click on details aside deploy/netlify.)

OK thanks!

**Comment by kiaking** [comment]
Hi! Thank you so much on working on this translations 🙏  Just to let you know, I'm planning to go through whole docs before stable release, and might restructure the contents here and there. So, please do not work too hard on this since I don't want to break your work badly 😅

**Comment by awxiaoxian2020** [comment]
> Hi! Thank you so much on working on this translations 🙏 Just to let you know, I'm planning to go through whole docs before stable release, and might restructure the contents here and there. So, please do not work too hard on this since I don't want to break your work badly 😅

Got it! Thanks!

**Comment by kiaking** [comment]
Hi! Seems like Evan had done whole doc rewrites and it's done now. I think you should expect that the doc is quite fixed 👍

**Comment by awxiaoxian2020** [comment]
@brc-dd Could we consider merging this PR now?

**Comment by brc-dd** [comment]
> Could we consider merging this PR now?

Yeah I'll ask the translations team to review it. 👍

**Comment by awxiaoxian2020** [comment]
> > Could we consider merging this PR now?
> 
> Yeah I'll ask the translations team to review it. 👍

It has many typos indeed. But maintaining it here by myself is so hard. It's so large.

**Comment by awxiaoxian2020** [comment]
Closing as support #2249.

**Pull request closed without merging**
